### ISSUE TITLE
Wrong positioning when nav bar is left and always visible

### ISSUE THREAD

**Issue by tim-peters** [jakmeier/aoe2-tools#1]
I got my windows nav bar on the left edge of the screen (instead of the bottom like usual) and it's turned to always visible. With this settings AoE is positioned wrong. There is a border on two sides of the screen and on the other there is some content cut off. It is not possible to correct this via the inbuild position setting, because this would need negative values. 

Tested on windows 10.

**Comment by jakmeier** [comment]
Hi, I've just tested the tool with the task bar on the left, the positioning is not different for me, but the delivered standard settings are probably not correct for you. However, for me there was some overlapping from the task bar with the game window, so I had to change the position x value to 100. After that, the position was fine, only the width of the window was too small. This was actually a bug, I was checking the user available width instead of the full screen size, so I've changed that and pushed it. 
Now it works for me even with the task bar on the left. But I'm not sure if that solves the problem you described, as I'm not even sure what your problem is. Why would you want a negative position value? That would put the game window outside of the visible screen. The position does generally not have to be changed at all, unless you want to have the window at a specific place in the screen. In this case, you want it to be outside of the task bar, so it makes sense to have some big enough x value, but negative values will not be of any help.
Please check again with the new version and let me know if the built in setting are enough to make it work now.

**Comment by tim-peters** [comment]
Jep, your update fixed it. Works fine now.

Thanks a lot for your effort! I really appreciate your work, making this game playable for everyone with a high-dpi screen.

**Comment by jakmeier** [comment]
Thank you for the feedback 👍
